### ISSUE TITLE
Blurry/Oversized icons

### ISSUE THREAD

**Issue by cj81499** [nickfrey/IconBundles#15]
It's fixed in Anemone, why not here?

https://github.com/AnemoneTeam/Anemone/issues/2

**Comment by nickfrey** [comment]
Anemone is closed-source, and the patch to IconBundles was not made open source by it's creators. Feel free to encourage Anemone's creators to provide me the patch or send it in as a pull request.

**Comment by cj81499** [comment]
I'll say something on twitter.

**Comment by cj81499** [comment]
Hey, I know this is kinda old, but maybe this will help.

https://www.reddit.com/r/iOSthemes/comments/3jg201/discussion_i_know_why_iconbundle_blurs_ipad/?
